services:
  postgresql:
    image: postgres:16.3-bullseye
    container_name: postgresql
    hostname: postgresql
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      POSTGRES_DB: ${DB_NAME:-pgdb}
      POSTGRES_USER: ${DB_USER:-uk}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-uk}
    volumes:
      - ${VOLUME_DIR:-./}:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -q -U $$POSTGRES_USER"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - postgresql_network

networks:
  postgresql_network:
    driver: bridge